TvShow/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'
  resources :tv_shows do
    member do
      post :add_to_favorites
      delete :remove_from_favorites
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

TvShow/app/models/channel.rb
class Channel < ApplicationRecord
    has_many :tv_series
end

TvShow/app/models/tv_series.rb
class TvSeries < ApplicationRecord
  acts_as_favoritable
  belongs_to :channel
  validates :name, :start_time, :end_time, :channel_id, presence: true
  def self.search(search)
    joins(:channel).where('tv_series.name like (?) OR channels.name like (?)', "%#{search}%", "%#{search}%")
   end 
end

TvShow/app/models/user.rb
class User < ApplicationRecord
  acts_as_favoritor
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

TvShow/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
  end

TvShow/app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
    def index
        if params[:search]
            # fetch only the records which matches with search content
            @tv_shows = TvSeries.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 5)
        else
            # fetch all the shows records
            @tv_shows = TvSeries.all.order("created_at DESC").paginate(page: params[:page], per_page: 5)
        end
        
    end


    def add_to_favorites
        @tv_show = Show.find(params[:id])
        if current_user.favorite(@tv_show)
          flash[:success] = 'Marked as favorite.'
        else
          flash[:alert] = 'Cannot mark favorite. Please try again later.'
        end
        redirect_back fallback_location: root_path
    end

    # method to remove tv show from favorites
    def remove_from_favorites
        @tv_show = Show.find(params[:id])
        if current_user.unfavorite(@tv_show)
            flash[:success] = 'Removed from favorites.'
        else
            flash[:alert] = 'Cannot remove from favorites. Please try again later.'
        end
        redirect_back fallback_location: root_path
    end    
end

TvShow/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

TvShow/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

TvShow/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

TvShow/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

TvShow/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

TvShow/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

TvShow/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  
  def index
  end
end

TvShow/app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(key)
	    case key
	      when 'notice' then 'info'
	      when 'success' then 'success'
	      when 'error' then 'danger'
	      when 'warning' then 'warning'
	      when 'alert' then 'danger'
	    end
	 end

end

TvShow/app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

TvShow/app/helpers/welcome_helper.rb
module WelcomeHelper
end

TvShow/app/views/layouts/_alerts.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= flash_class(key) %> alert-dismissible fade show" role="alert">
      <%= value %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
    
   update app/views/layouts/application.html.erb
      update /home/kishan/project/tv_show_new/app/views/layouts/application.html.erb
      <!DOCTYPE html>
      <html>
        <head>
          <title>FavShow</title>
          <%= csrf_meta_tags %>
  
          <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
          <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        </head>
  
        <body>
          <%= render 'layouts/navbar' %>
          <div class="container mt-4">
            <%= render 'layouts/alerts' %>
            <%= yield %>
          </div>
        </body>
      </html>
  

TvShow/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvShow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

TvShow/app/views/tv_shows/_search.html.erb
<%= form_tag(tv_shows_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Shows" %>
    <%= submit_tag "Search" %>
  <% end %>
  

TvShow/app/views/tv_shows/_tv_show.html.erb
<%= render @tv_shows %>

<tr>
  <td><%= tv_show.name %></td>
  <td><%= tv_show&.channel&.name %></td>
  <td><%= tv_show.start_time.strftime("%I:%M %p") + ' - ' + tv_show.end_time.strftime("%I:%M %p") %></td>
  <td>
    <% if user_signed_in? && current_user.favorited?(tv_show) %>
      <%= link_to 'Remove from favorites', remove_from_favorites_tv_show_path(tv_show), method: :delete, class: 'btn btn-danger btn-sm' %>
    <% else %>
      <%= link_to 'Add to favorites', add_to_favorites_tv_show_path(tv_show), method: :post, class: 'btn btn-primary btn-sm' %>
    <% end %>
  </td>
</tr>