ecommerce/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resources :products
  resources :carts do
    member do
      patch :change_status
    end
  end
  resources :order_items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

ecommerce/app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image, ProductImageUploader

    # serialize :image, JSON
    before_destroy :not_referenced_by_any_order_item
    belongs_to :user, optional: true
    has_many :order_items
    validates :name, :description, :condition, :price, :image, presence: true
    validates :price, length: {maximum: 7 }
  
    CONDITION = %w{ New Excellent Mint Used Failr Poor}
  
    def not_referenced_by_any_order_item
      unless order_items.empty?
        errors.add(:base, "Order Items present")
        throw :abort
      end
    end
end

ecommerce/app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base

    layout 'index', only: [:index, :show]
  
    before_action :set_product, only: %i[ show edit update destroy ]
    before_action :authenticate_user!, except: [:index, :show]
    # before_action :correct_user, only: [:edit, :update, :destroy]
    # GET /user_lists or /user_lists.json
    def index
      @products = Product.all
      return @products
    end
  
    # GET /user_lists/1 or /user_lists/1.json
    def show
    end
  
    # GET /user_lists/new
    def new
      @product = current_user.products.build
    end
  
    # GET /user_lists/1/edit
    def edit
      # @product = Product.find(params[:id])
    end
  
    # POST /user_lists or /user_lists.json
    def create
      @product = current_user.products.build(product_params)
  
      respond_to do |format|
        if @product.save
          format.html { redirect_to products_url(@product), notice: "Product was successfully created." }
          format.json { render :index, status: :created, location: @product }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /user_lists/1 or /user_lists/1.json
    def update
      # @product = Product.find(params[:id])
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to products_url(@product), notice: "Product was successfully updated." }
          format.json { render :index, status: :ok, location: @product }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /user_lists/1 or /user_lists/1.json
    def destroy
      
      # @product = Product.find(params[:id])
      if @product.present?
      @product.destroy
      end
      respond_to do |format|
        format.html { redirect_to products_url, notice: "Product  was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    # def correct_user
    #   @friend = current_user.user_lists.find_by(id: params[:id])
    #   redirect_to user_list_path, notice: "Not Autherized to edit this user" if @friend.nil?
    # end
  
    private
    #   # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end
  
      def product_params
        params.require(:product).permit(:name, :description, :condition, :price, :image)
      end
  
  end
  
  
  

ecommerce/app/helpers/products_helper.rb
module ProductsHelper
end

ecommerce/app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
    <% if @product.errors.any? %>
      <% @product.errors.full_messages.each do |message| %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert" id="alert">
          <%= message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    <% end %>
    <div class="field mb-3">
      <%= f.text_field :name, required: true, autofocus: true, class:"form-control", placeholder:"Product Name" %>
    </div>
    <div class="field  mb-3">
      <%= f.number_field :price, required: true, class:"form-control", maxlength: 7 %>
    </div>
    <div class="field mb-3">
      <%= f.text_area :description, required: true, class:"form-control", placeholder:"Product Description" %>
    </div>
    <div class="field mb-3 form-control">
      <%= f.select :condition, collection: Product::CONDITION %>
    </div>
    <div class="field mb-3">
      <%= f.file_field :image, class:"form-control" %>
    </div>
    <output id="list"></output>
    <div class="mb-3 field">
      <%= f.button :submit, class: 'btn btn-secondary'   %>
      <%= link_to 'Cancel', products_path, class:'btn btn-dark' %>
    </div>
  <% end %>
  

ecommerce/app/views/products/_product.html.erb
<div class="h-100 p-5 bg-white border rounded-3 row">
    <div class="col">
      <p>
        <img src="<%= product.image.url%>"/>
      </p>
    </div>
    <div class="col">
              <h2>
              <%= @product.name %>
              </h2>
              <br /><br />
              <p>
                <strong>Description: </strong>
                <%= product.description %>
              </p>

              <p>
                <strong>Condition: </strong>
                <%= product.condition %>
              </p>

              <p>
                <strong>Price: </strong>
                <%= number_to_currency(product.price) %>
              </p>
              <p>  <strong>Sold By: </strong> <%= @product.user.name %></p>

            
              <br/><br/>
      <% if(current_user.id ==  @product.user_id) %>
              <%= link_to "Edit", edit_product_path(@product),  class:"btn btn-secondary" %>
              <% else %>
              <div class="d-flex">
               <%= button_to 'Add to cart', order_items_path(product_id: @product), class: 'btn btn-secondary', style: 'margin-right : 15px' %>
      <% end %>
              <%= link_to "Back", products_path,  class:"btn btn-dark ml-5" %>
              </div>
              <%# <%= link_to "Destroy", @product, method: :delete,  class:"btn btn-danger" %> 
               
    </div>
</div>

ecommerce/app/views/products/edit.html.erb
<div class="card">
<div class="card-header">
<h1>Editing product</h1>
</div>
<div class="card-body">
<%= render 'form', instrument: @product %>
</div>
</div>

ecommerce/app/views/products/index.html.erb
<% if notice%>
  <div class="alert alert-warning alert-dismissible fade show" role="alert" id="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<h1>Products</h1>
<div class="wrapper">
  <div class="container">
    <div class="row g-1">
    <%  @products.each do |product| %>
      <div class="col-md-3">
        <div class="card p-3 m-3">
          <div class="text-center">
              <%= link_to image_tag(product.image.url, :width => "200", :height => "200"), product_path(product.id) %>
          </div>
          <div class="product-details mt-2">
            <p class="d-block price"><%= number_to_currency(product.price) %></p>
            <p><%= product.name %></p>
            <% if(current_user.id !=  product.user_id) %>
            <div class="buttons d-flex flex-row">
              <div class="cart"><i class="fa fa-shopping-cart"></i></div>
              <button class="btn btn-success cart-button btn-block"><span class="dot">1</span>Add to cart </button>
            </div>
            <div class="weight">
              <small>1 Item</small>
            </div>
            <% else %>
             <div class="buttons d-flex flex-row justify-content-around">
                    <%= link_to 'Edit', edit_product_url(product), class: "btn btn-outline-secondary" %>
                    <%= link_to "Delete", product, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} ,class:'btn  btn-outline-danger'%>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function(event) {


  const cartButtons = document.querySelectorAll('.cart-button');

  cartButtons.forEach(button => {

  button.addEventListener('click',cartClick);

  });

  function cartClick(){
  let button =this;
  button.classList.add('clicked');
  }



  });
</script>

ecommerce/app/views/products/new.html.erb
<div class="card">
<div class="card-header">
 <h1>New product</h1>
</div>
<div class="card-body">
<%= render 'form', instrument: @product %>
</div>
<%# <div>
<%= link_to "Back to products", products_path %>
<%# </div>  %>
</div>

ecommerce/app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @product  %>