ecommerce/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resources :products
  resources :carts do
    member do
      patch :change_status
    end
  end
  resources :order_items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

ecommerce/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

ecommerce/app/helpers/home_helper.rb
module HomeHelper
end

ecommerce/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
   
   <%= link_to 'Ecommerce',root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        
        <%# <li class="nav-item">
        <%= link_to 'All Users',home_about_path, class: 'nav-link' %>
        <%# </li> %>
        
         

        <% if user_signed_in? %>

        <li class="nav-item">
        <%= link_to 'Products',products_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
        <%= link_to 'Add Product',new_product_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
        <%= link_to 'Sign Out',destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'nav-link' %>
        </li>

        <li class="nav-item">
        <%= link_to 'Edit Profile',edit_user_registration_path, class: 'nav-link' %>
        </li>

        <% else %>

        <li class="nav-item">
        <%= link_to 'Sign Up',new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to 'Sign In',new_user_session_path, class: 'nav-link' %>
        </li>

        <% end %>
          <% if cart_has_items %>
         <li class="nav-item">
              <%= link_to cart_path(@cart), class:"nav-link"  do %> 
              <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
              </span>
             <span>
                <%= cart_count_over_one  %>
                </span>
               <% end %>
               </li>
            <% end %>
            <li class="nav-item">
            <%= link_to 'History',carts_path, class: 'nav-link' %>
            </li>
            
      </ul>
    </div>
  </div>
</nav>

ecommerce/app/views/home/index.html.erb
<% if user_signed_in? %>
<h1>Welcome <%= current_user.name %> !</h1>
<% else %>
<h1>Hello Guest ! </h1>
<% end %>